services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ecommerce_ai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
